-- Набор команд для создания базы данных и пользователя с полными правами на только что созданную БД
CREATE DATABASE IF NOT EXISTS `YOUR_DB_NAME` CHARACTER SET utf8 COLLATE utf8_general_ci;
CREATE USER 'YOUR_DB_USER'@'localhost' IDENTIFIED BY 'YOUR_DB_USER_PASSWORD';
GRANT USAGE ON *.* TO 'YOUR_DB_USER'@'localhost' IDENTIFIED BY 'YOUR_DB_USER_PASSWORD' REQUIRE NONE WITH MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0;
GRANT ALL PRIVILEGES ON `YOUR_DB_NAME`.* TO 'YOUR_DB_USER'@'localhost' WITH GRANT OPTION;
FLUSH PRIVILEGES;